server:
  port: 8080

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: kubuski01
    password: Kubuski01@postgres
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
